#!/usr/bin/python3



import os

import jk_infodatatree





OUTPUT_DIR_PATH = "."







docuFilePath = os.path.join(OUTPUT_DIR_PATH, "Data types (autogenerated).md")
with open(docuFilePath, "w") as f:
	f.write(jk_infodatatree.generateValueDataTypeDocu())








